update dependency versions to align with WildFly 10 Beta 2; fix movies.jrxml (change language="groovy" to "java") and recompile it to movies.jasper, which is used as jasper template by tests.  This is to avoid errors like "NoClassDefFoundError: org/codehaus/groovy/control/CompilationFailedException"